FROM wpilib/ubuntu-base:22.04

# Install WPILib
RUN wget https://packages.wpilib.workers.dev/installer/v2024.3.2/Linux/WPILib_Linux-2024.3.2.tar.gz -O wpilib.tar.gz
RUN mkdir -p /root/wpilib/2024
RUN tar -zxvf wpilib.tar.gz -C /root/wpilib/2024